name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    # Fetch and pull latest changes from GitHub repository
    - name: Fetch latest changes
      run: git fetch origin main

    - name: Pull latest changes
      run: git pull origin main

    # Restart PM2 process after pulling latest changes
    - name: Restart PM2 process
      run: pm2 restart bajivaibackend
